Add  Hello World
ecekpo/Hello-world pull request #1
Opened 2022-05-25 11:34 UTC by ecekpo

![image](https://user-images.githubusercontent.com/101729024/170252730-3b8fd795-8ba7-4c45-83d4-2dd65c8a5833.png)

2022-05-25 12:33 UTC, Kossi-stack requested changes
**Hi @ecekpo ,**

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages is meaningful.

## Required Changes ♻️

 - [ ] Kindly edit the PR's title to something more descriptive. it can be "Hello Microverse Project PR or Hello Microverse Project".
 - [ ] Kindly remove the image you put in the pull request message and put it the readme file.
 - [ ] Kindly add descriptive pull request message, This helps other programmers who want to take a look at your code understand what changes you made to a particular branch.
 
 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-25 12:33 UTC, Kossi-stack commented on .github/workflows
> -
- [ ] kindly remove this file

2022-05-25 12:33 UTC, Kossi-stack commented on README.md
> +
- [ ] Kindly remove all the empty space in the readme file.

2022-05-25 12:33 UTC, Kossi-stack commented on README.md
> +> HTML Hello World Project
- [ ] kindly remove this line, this is Hello Microverse Project it is not a hello word project also add a descriptive message of the project.

2022-05-26 09:47 UTC, ecekpo commented on .github/workflows
> -
This file is from github super linters. The instructions said we should add them.

2022-05-26 09:50 UTC, ecekpo commented on .github/workflows
> -
This file is from linters
Should we change the instructions?
Please check the instructions again

2022-05-26 11:20 UTC, ecekpo commented on README.md
> +
Removing the empty space will take away the bullets

2022-05-26 11:35 UTC, chrystalme approved these changes
# Hi @ecekpo, 

## Project Status ✅ Approve
![giphy](https://user-images.githubusercontent.com/12239821/170479833-7d512e16-01cb-475c-bd04-cf0984cd30b9.gif)


In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 

## Optional Requirement
- In your next project, avoid committing `.vscode/` to your repo. This makes your repo unprofessional.
- Also, be consistent with your git commit. Start every commit with a capital letter.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Also, you can reach me on [Twitter](https://twitter.com/afam_ifeanyi) or [Slack](https://microverse-community.slack.com/team/U019ZC99KFA)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 13:33 UTC, merged